"""empty message

Revision ID: 341e2c841f14
Revises: 
Create Date: 2025-08-27 10:46:25.294699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341e2c841f14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tanque', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.String(length=3), nullable=True),
    sa.Column('unidade', sa.String(length=100), nullable=False),
    sa.Column('capex', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('link_google_drive', sa.String(length=255), nullable=False),
    sa.Column('becus_id', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao', sa.String(length=255), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('visita', sa.Date(), nullable=True),
    sa.Column('desenhista', sa.String(length=100), nullable=True),
    sa.Column('timestamp_inicio', sa.DateTime(), nullable=True),
    sa.Column('timestamp_final', sa.DateTime(), nullable=True),
    sa.Column('revisor', sa.String(length=100), nullable=True),
    sa.Column('correcoes', sa.Text(), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('art', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('projeto')
    op.drop_table('user')
    op.drop_table('unidades')
    op.drop_table('cliente')
    # ### end Alembic commands ###
