"""empty message

Revision ID: 387b806c2416
Revises: 9a359cd653fe
Create Date: 2025-09-12 15:11:47.188689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387b806c2416'
down_revision = '9a359cd653fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('visita',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('visita',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
