"""empty message

Revision ID: 9302c85435c7
Revises: df2f3a36ee65
Create Date: 2025-09-29 14:30:50.125295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9302c85435c7'
down_revision = 'df2f3a36ee65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('data_entrega',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('data_entrega',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
