"""empty message

Revision ID: 9a359cd653fe
Revises: b3b2d1b40039
Create Date: 2025-09-12 15:10:23.717556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a359cd653fe'
down_revision = 'b3b2d1b40039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('prazo',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('visita',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('visita',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('prazo',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
