"""empty message

Revision ID: a0ce7ce97803
Revises: 387b806c2416
Create Date: 2025-09-12 15:13:17.502767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ce7ce97803'
down_revision = '387b806c2416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('data_entrega',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('data_entrega',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
