"""empty message

Revision ID: b3b2d1b40039
Revises: 7df90ea812ed
Create Date: 2025-09-12 14:32:31.326731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b2d1b40039'
down_revision = '7df90ea812ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correcao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.drop_column('corrigida')

    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('art',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.alter_column('art',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('correcao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corrigida', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
